module.exports = {
  // source code type, 'js' or 'ts'. 源码类型
  srcType: 'js',
  // name for UMD export. e.g., 'myLib' or 'lib.util'. UMD模式全局变量名
  umdName: 'loganUmdName',
  // Code to insert at top of bundle (outside wrapper). 打包文件头部内容
  banner: `/*!
  * Generated by @logan/jslib-base. (https://github.com/logan70/jslib)
  * Copyright 2018-${(new Date).getFullYear()} logan70. All Rights Reserved
  * Licensed under MIT (https://github.com/logan70/jslib/blob/master/LICENSE)
  */`,
  // Code to insert at end of bundle (outside wrapper). 打包文件尾部内容
  footer: '/* Generated by @logan/jslib-base. https://github.com/logan70/jslib */',
  // output files of different module specification. 各模块规范的输出文件
  output: {
    umd: 'dist/index.aio.js',
    umdMin: 'dist/index.aio.min.js',
    esm: 'dist/index.esm.js',
    cjs: 'dist/index.js',
  },
  // Should documents be auto-generated, true or false. 是否自动生成API文档
  requireDocs: true,
  // JSDoc Configuration file. JSDoc配置文件位置
  jsDocConfigPath: 'build/plugin-doc/jsdocConf.js',
  // TypeDoc Configuration file. TypeDoc配置文件位置
  tsDocConfigPath: 'build/plugin-doc/tsdocConf.js',
  // disable ESLint/TSLint or not, true or false. 禁用代码风格检查
  disableLint: false,
  // if true, will block build if any lint error or warnings were found . 代码风格检查出错时终止构建（build）
  blockBuildOnLintFailures: true
}